name: Build

on:
  pull_request:
      types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          # only amd64 so the image can be loaded
          platforms: linux/amd64
          context: ./picapport
          tags: mwgevans/picapport:test
          push: false
          load: true
      - name: Start Container Test
        run: docker run -d --rm --name testcontainer mwgevans/picapport:test
      - name: Wait for container
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: testcontainer
          wait-time: 50
          require-status: running
          require-healthy: true
#      - name: Test image
#        uses: addnab/docker-run-action@v3
#        with:
#          image: mwgevans/picapport:test
#          run: "/bin/sh /github-influx.sh"
#          options: "-e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
